import { NAME } from './constants';

export const CREATE_RECORD_REQUEST = `${NAME}/CREATE_RECORD/REQUEST`;
export const CREATE_RECORD_SUCCESS = `${NAME}/CREATE_RECORD/SUCCESS`;
export const CREATE_RECORD_FAILURE = `${NAME}/CREATE_RECORD/FAILURE`;

export const UPDATE_RECORD_REQUEST = `${NAME}/UPDATE_RECORD/REQUEST`;
export const UPDATE_RECORD_SUCCESS = `${NAME}/UPDATE_RECORD/SUCCESS`;
export const UPDATE_RECORD_FAILURE = `${NAME}/UPDATE_RECORD/FAILURE`;

export const REPLACE_RECORD_REQUEST = `${NAME}/REPLACE_RECORD/REQUEST`;
export const REPLACE_RECORD_SUCCESS = `${NAME}/REPLACE_RECORD/SUCCESS`;
export const REPLACE_RECORD_FAILURE = `${NAME}/REPLACE_RECORD/FAILURE`;

export const DELETE_RECORD_REQUEST = `${NAME}/DELETE_RECORD/REQUEST`;
export const DELETE_RECORD_SUCCESS = `${NAME}/DELETE_RECORD/SUCCESS`;
export const DELETE_RECORD_FAILURE = `${NAME}/DELETE_RECORD/FAILURE`;

export const FETCH_RECORD_REQUEST = `${NAME}/FETCH_RECORD/REQUEST`;
export const FETCH_RECORD_SUCCESS = `${NAME}/FETCH_RECORD/SUCCESS`;
export const FETCH_RECORD_FAILURE = `${NAME}/FETCH_RECORD/FAILURE`;

export const FETCH_COLLECTION_REQUEST = `${NAME}/FETCH_COLLECTION/REQUEST`;
export const FETCH_COLLECTION_SUCCESS = `${NAME}/FETCH_COLLECTION/SUCCESS`;
export const FETCH_COLLECTION_FAILURE = `${NAME}/FETCH_COLLECTION/FAILURE`;
