export const NAME = 'goals';

// Filter types
export const REMAINING_GOALS_FILTER = 'REMAINING_GOALS_FILTER';
export const COMPLETED_GOALS_FILTER = 'COMPLETED_GOALS_FILTER';
export const ALL_GOALS_FILTER = 'ALL_GOALS_FILTER';
export const filters = { REMAINING_GOALS_FILTER, COMPLETED_GOALS_FILTER, ALL_GOALS_FILTER };
