export const NAME = 'goals';

const REMAINING_FILTER = 'REMAINING_FILTER';
const COMPLETED_FILTER = 'COMPLETED_FILTER';
const ALL_FILTER = 'ALL_FILTER';
export const filters = { REMAINING_FILTER, COMPLETED_FILTER, ALL_FILTER };
